name: bit_set
version: 0.2.0-dev
author: Andrew Skalkin <skalkin@gmail.com>
description: Efficient implementation of a bitset.
homepage: https://github.com/skalkin/bit_set
dev_dependencies:
  test: any
